package com.sonymobile.generativeartwork.render;

import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.opengl.GLES11Ext;
import android.opengl.GLES20;
import android.opengl.Matrix;
import android.util.Log;
import androidx.work.Data;
import com.sonymobile.generativeartwork.layers.GenerativeLayer;
import com.sonymobile.generativeartwork.utils.Utils;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.ListIterator;
import javax.microedition.khronos.egl.EGL10;
import javax.microedition.khronos.egl.EGLConfig;
import javax.microedition.khronos.egl.EGLContext;
import javax.microedition.khronos.egl.EGLDisplay;
import javax.microedition.khronos.egl.EGLSurface;

/* JADX INFO: loaded from: classes2.dex */
public class OffscreenRenderer {
    private static final int EGL_ALPHA_SIZE_IDX = 7;
    private static final int EGL_BLUE_SIZE_IDX = 5;
    private static final int EGL_CONTEXT_CLIENT_VERSION = 12440;
    private static final int EGL_DEPTH_SIZE_IDX = 9;
    private static final int EGL_GREEN_SIZE_IDX = 3;
    private static final int EGL_RED_SIZE_IDX = 1;
    private static final int EGL_STENCIL_SIZE_IDX = 11;
    private static final int NUM_OFFSCREEN_BUFFS = 2;
    private static final int NUM_OFFSCREEN_TEXTURES = 3;
    private static int OES_TEXTURE_IDX = 2;
    private static final String TAG = "com.sonymobile.generativeartwork.render.OffscreenRenderer";
    public static final String UNIQUE_ID = "Generated by Sony GAW:1.0";
    static final int mNumSignaturePxls;
    static final byte[] mSignatureData;
    static final int mSignatureLength;
    private int[] mConfigSpec;
    private EGL10 mEgl;
    private EGLConfig mEglConfig;
    private float[] mGlobalTransform;
    private int mHeight;
    private ByteBuffer mResBuffer;
    private Canvas mTempCanvas;
    private int mWidth;
    private int[] mSignaturePixels = new int[mNumSignaturePxls];
    private int[] mOffscreenTexture = new int[3];
    private int[] mFBO = new int[2];
    private boolean isOESFBSupported = false;
    private int mOESFBO = -1;
    private int mCurrentFB = 0;
    private int mCurrentTexture = 0;
    private int mPBO = -1;
    private int mPBOSize = 0;
    private EGLDisplay mEglDisplay = EGL10.EGL_NO_DISPLAY;
    private EGLSurface mEglSurface = EGL10.EGL_NO_SURFACE;
    private EGLContext mEglContext = EGL10.EGL_NO_CONTEXT;
    private EGLContext mEglOriginalContext = EGL10.EGL_NO_CONTEXT;
    private EGLSurface mEglOriginalSurfaceDraw = EGL10.EGL_NO_SURFACE;
    private EGLSurface mEglOriginalSurfaceRead = EGL10.EGL_NO_SURFACE;
    private EGLDisplay mEglOriginalDisplay = EGL10.EGL_NO_DISPLAY;
    private boolean mNeedContextSwitch = false;
    private int mClearingBits = 0;
    private boolean mScissorsEnabled = false;

    public enum Mode {
        Stretch,
        CutTL
    }

    static {
        byte[] bytes = UNIQUE_ID.getBytes(Charset.forName("US-ASCII"));
        mSignatureData = bytes;
        int length = bytes.length;
        mSignatureLength = length;
        mNumSignaturePxls = length * 2;
    }

    public OffscreenRenderer() {
        float[] fArr = new float[16];
        this.mGlobalTransform = fArr;
        Matrix.setIdentityM(fArr, 0);
        Matrix.scaleM(this.mGlobalTransform, 0, 1.0f, -1.0f, 1.0f);
        this.mTempCanvas = new Canvas();
    }

    public void init(int i, int i2, int i3, int i4, int i5, int i6, int i7, int i8) {
        this.mWidth = i7;
        this.mHeight = i8;
        EGL10 egl10 = (EGL10) EGLContext.getEGL();
        this.mEgl = egl10;
        EGLDisplay eGLDisplayEglGetDisplay = egl10.eglGetDisplay(EGL10.EGL_DEFAULT_DISPLAY);
        this.mEglDisplay = eGLDisplayEglGetDisplay;
        if (eGLDisplayEglGetDisplay == EGL10.EGL_NO_DISPLAY) {
            throw new RuntimeException("eglGetDisplay failed");
        }
        if (!this.mEgl.eglInitialize(this.mEglDisplay, new int[2])) {
            throw new RuntimeException("eglInitialize failed");
        }
        this.mConfigSpec = new int[]{12324, i, 12323, i2, 12322, i3, 12321, i4, 12325, i5, 12326, i6, 12339, 1, 12354, 4, 12352, 4, 12346, 1, 12344};
        this.mClearingBits = 16384;
        if (i5 != 0) {
            this.mClearingBits = 16384 | 256;
        }
        EGLConfig eGLConfigChooseConfig = chooseConfig(this.mEgl, this.mEglDisplay);
        this.mEglConfig = eGLConfigChooseConfig;
        EGLContext eGLContextEglCreateContext = this.mEgl.eglCreateContext(this.mEglDisplay, eGLConfigChooseConfig, EGL10.EGL_NO_CONTEXT, new int[]{EGL_CONTEXT_CLIENT_VERSION, 2, 12344});
        this.mEglContext = eGLContextEglCreateContext;
        if (eGLContextEglCreateContext == null || eGLContextEglCreateContext == EGL10.EGL_NO_CONTEXT) {
            this.mEglContext = null;
            throw new RuntimeException("eglCreateContext failed");
        }
        int i9 = this.mWidth * this.mHeight * 4;
        this.mPBOSize = i9;
        this.mResBuffer = ByteBuffer.allocateDirect(i9).order(ByteOrder.nativeOrder());
        EGLSurface eGLSurfaceEglCreatePbufferSurface = this.mEgl.eglCreatePbufferSurface(this.mEglDisplay, this.mEglConfig, new int[]{12375, this.mWidth, 12374, this.mHeight, 12416, 12382, 12417, 12383, 12344});
        this.mEglSurface = eGLSurfaceEglCreatePbufferSurface;
        if ((eGLSurfaceEglCreatePbufferSurface == null || eGLSurfaceEglCreatePbufferSurface == EGL10.EGL_NO_SURFACE) && this.mEgl.eglGetError() == 12299) {
            throw new RuntimeException("eglCreatePbufferSurface has failed");
        }
        makeCurrentIfNeeded();
        this.isOESFBSupported = GLES20.glGetString(7939).contains("GL_OES_framebuffer_object");
        GLES20.glClearColor(0.25f, 0.25f, 0.25f, 1.0f);
        createOffscreenBuffs();
    }

    public void release() {
        int[] iArr = new int[3];
        System.arraycopy(this.mFBO, 0, iArr, 0, 2);
        GLES20.glDeleteFramebuffers(2, iArr, 0);
        if (this.isOESFBSupported) {
            iArr[0] = this.mOESFBO;
            GLES11Ext.glDeleteFramebuffersOES(1, iArr, 0);
        }
        System.arraycopy(this.mOffscreenTexture, 0, iArr, 0, 3);
        GLES20.glDeleteTextures(3, iArr, 0);
        restoreContextIfNeeded();
        this.mEgl.eglDestroySurface(this.mEglDisplay, this.mEglSurface);
        this.mEgl.eglDestroyContext(this.mEglDisplay, this.mEglContext);
        this.mEgl.eglTerminate(this.mEglDisplay);
    }

    public void makeCurrentIfNeeded() {
        this.mEglOriginalContext = this.mEgl.eglGetCurrentContext();
        this.mEglOriginalSurfaceDraw = this.mEgl.eglGetCurrentSurface(12377);
        this.mEglOriginalSurfaceRead = this.mEgl.eglGetCurrentSurface(12378);
        EGLDisplay eGLDisplayEglGetCurrentDisplay = this.mEgl.eglGetCurrentDisplay();
        this.mEglOriginalDisplay = eGLDisplayEglGetCurrentDisplay;
        EGLContext eGLContext = this.mEglOriginalContext;
        EGLContext eGLContext2 = this.mEglContext;
        if (eGLContext == eGLContext2) {
            EGLSurface eGLSurface = this.mEglOriginalSurfaceDraw;
            EGLSurface eGLSurface2 = this.mEglSurface;
            if (eGLSurface == eGLSurface2 && this.mEglOriginalSurfaceRead == eGLSurface2 && eGLDisplayEglGetCurrentDisplay == this.mEglDisplay) {
                return;
            }
        }
        EGL10 egl10 = this.mEgl;
        EGLDisplay eGLDisplay = this.mEglDisplay;
        EGLSurface eGLSurface3 = this.mEglSurface;
        if (egl10.eglMakeCurrent(eGLDisplay, eGLSurface3, eGLSurface3, eGLContext2)) {
            this.mNeedContextSwitch = true;
        } else {
            Log.e(TAG, "Can't perform context switch, err: " + this.mEgl.eglGetError());
        }
    }

    public void restoreContextIfNeeded() {
        if (this.mNeedContextSwitch) {
            if (this.mEgl.eglMakeCurrent(this.mEglOriginalDisplay, this.mEglOriginalSurfaceDraw, this.mEglOriginalSurfaceRead, this.mEglOriginalContext)) {
                this.mNeedContextSwitch = false;
            } else {
                Log.e(TAG, " disp: " + this.mEglOriginalDisplay + " Can't restore original context, err: " + this.mEgl.eglGetError() + " maybe was no context bound before.");
            }
        }
    }

    private EGLConfig chooseConfig(EGL10 egl10, EGLDisplay eGLDisplay) {
        int[] iArr = new int[1];
        if (!egl10.eglChooseConfig(eGLDisplay, this.mConfigSpec, null, 0, iArr)) {
            throw new IllegalArgumentException("eglChooseConfig failed");
        }
        int i = iArr[0];
        if (i <= 0) {
            throw new IllegalArgumentException("No configs match configSpec");
        }
        EGLConfig[] eGLConfigArr = new EGLConfig[i];
        if (!egl10.eglChooseConfig(eGLDisplay, this.mConfigSpec, eGLConfigArr, i, iArr)) {
            throw new IllegalArgumentException("eglChooseConfig#2 failed");
        }
        EGLConfig eGLConfigFindConfig = findConfig(egl10, eGLDisplay, eGLConfigArr);
        if (eGLConfigFindConfig != null) {
            return eGLConfigFindConfig;
        }
        throw new IllegalArgumentException("No config chosen");
    }

    private EGLConfig findConfig(EGL10 egl10, EGLDisplay eGLDisplay, EGLConfig[] eGLConfigArr) {
        for (EGLConfig eGLConfig : eGLConfigArr) {
            int iFindConfigAttrib = findConfigAttrib(egl10, eGLDisplay, eGLConfig, 12325, 0);
            int iFindConfigAttrib2 = findConfigAttrib(egl10, eGLDisplay, eGLConfig, 12326, 0);
            int[] iArr = this.mConfigSpec;
            if (iFindConfigAttrib >= iArr[9] && iFindConfigAttrib2 >= iArr[11]) {
                int iFindConfigAttrib3 = findConfigAttrib(egl10, eGLDisplay, eGLConfig, 12324, 0);
                int iFindConfigAttrib4 = findConfigAttrib(egl10, eGLDisplay, eGLConfig, 12323, 0);
                int iFindConfigAttrib5 = findConfigAttrib(egl10, eGLDisplay, eGLConfig, 12322, 0);
                int iFindConfigAttrib6 = findConfigAttrib(egl10, eGLDisplay, eGLConfig, 12321, 0);
                int[] iArr2 = this.mConfigSpec;
                if (iFindConfigAttrib3 == iArr2[1] && iFindConfigAttrib4 == iArr2[3] && iFindConfigAttrib5 == iArr2[5] && iFindConfigAttrib6 == iArr2[7]) {
                    return eGLConfig;
                }
            }
        }
        return null;
    }

    private int findConfigAttrib(EGL10 egl10, EGLDisplay eGLDisplay, EGLConfig eGLConfig, int i, int i2) {
        int[] iArr = new int[1];
        return egl10.eglGetConfigAttrib(eGLDisplay, eGLConfig, i, iArr) ? iArr[0] : i2;
    }

    private void createOffscreenBuffs() {
        int[] iArr = new int[3];
        GLES20.glGenTextures(3, iArr, 0);
        Utils.checkGLErr();
        GLES20.glActiveTexture(33984);
        Utils.checkGLErr();
        for (int i = 0; i < 3; i++) {
            int[] iArr2 = this.mOffscreenTexture;
            iArr2[i] = iArr[i];
            GLES20.glBindTexture(3553, iArr2[i]);
            Utils.checkGLErr();
            GLES20.glTexImage2D(3553, 0, 6408, this.mWidth, this.mHeight, 0, 6408, 5121, null);
            Utils.checkGLErr();
            GLES20.glTexParameteri(3553, 10241, 9728);
            Utils.checkGLErr();
            GLES20.glTexParameteri(3553, Data.MAX_DATA_BYTES, 9728);
            Utils.checkGLErr();
            GLES20.glTexParameteri(3553, 10242, 10497);
            Utils.checkGLErr();
            GLES20.glTexParameteri(3553, 10243, 10497);
            Utils.checkGLErr();
        }
        GLES20.glGenFramebuffers(2, iArr, 0);
        Utils.checkGLErr();
        for (int i2 = 0; i2 < 2; i2++) {
            int[] iArr3 = this.mFBO;
            iArr3[i2] = iArr[i2];
            GLES20.glBindFramebuffer(36160, iArr3[i2]);
            Utils.checkGLErr();
            GLES20.glFramebufferTexture2D(36160, 36064, 3553, this.mOffscreenTexture[i2], 0);
            Utils.checkGLErr();
            GLES20.glViewport(0, 0, this.mWidth, this.mHeight);
            Utils.checkGLErr();
        }
        if (this.isOESFBSupported) {
            GLES11Ext.glGenFramebuffersOES(1, iArr, 0);
            int i3 = iArr[0];
            this.mOESFBO = i3;
            GLES11Ext.glBindFramebufferOES(36160, i3);
            Utils.checkGLErr();
            GLES11Ext.glFramebufferTexture2DOES(36160, 36064, 3553, this.mOffscreenTexture[OES_TEXTURE_IDX], 0);
            Utils.checkGLErr();
            GLES20.glViewport(0, 0, this.mWidth, this.mHeight);
            Utils.checkGLErr();
        }
        GLES20.glBindFramebuffer(36160, 0);
        Utils.checkGLErr();
    }

    public void render(Bitmap bitmap, ArrayList<GenerativeLayer> arrayList) {
        this.mCurrentFB = 0;
        int size = arrayList.size();
        ListIterator<GenerativeLayer> listIterator = arrayList.listIterator();
        resetGlobalTransform();
        for (int i = 0; i < size - 1; i++) {
            GLES20.glBindFramebuffer(36160, this.mFBO[this.mCurrentFB]);
            listIterator.next().draw(this.mGlobalTransform);
            int[] iArr = this.mOffscreenTexture;
            int i2 = this.mCurrentFB;
            this.mCurrentTexture = iArr[i2];
            this.mCurrentFB = (i2 + 1) % 2;
        }
        GLES20.glBindFramebuffer(36160, 0);
        listIterator.next().draw(this.mGlobalTransform);
        this.mResBuffer.position(0);
        GLES20.glReadPixels(0, 0, this.mWidth, this.mHeight, 6408, 5121, this.mResBuffer);
        Utils.checkGLErr();
        this.mResBuffer.position(0);
        bitmap.copyPixelsFromBuffer(this.mResBuffer);
        this.mTempCanvas.setBitmap(bitmap);
        for (GenerativeLayer generativeLayer : arrayList) {
            if (!generativeLayer.isOpenGLLayer()) {
                generativeLayer.draw(this.mTempCanvas);
            }
        }
    }

    public void render(Bitmap bitmap, ArrayList<GenerativeLayer> arrayList, Mode mode) {
        int width = bitmap.getWidth();
        int height = bitmap.getHeight();
        int i = this.mWidth;
        int i2 = i < width ? i : width;
        int i3 = this.mHeight;
        int i4 = i3 < height ? i3 : height;
        this.mCurrentFB = 0;
        int size = arrayList.size();
        ListIterator<GenerativeLayer> listIterator = arrayList.listIterator();
        for (int i5 = 0; i5 < size - 1; i5++) {
            GLES20.glBindFramebuffer(36160, this.mFBO[this.mCurrentFB]);
            listIterator.next().draw(this.mGlobalTransform);
            int[] iArr = this.mOffscreenTexture;
            int i6 = this.mCurrentFB;
            this.mCurrentTexture = iArr[i6];
            this.mCurrentFB = (i6 + 1) % 2;
        }
        if (this.mWidth >= i2 || this.mHeight >= i4) {
            setupGlobalTransform(i2, i4, mode);
        }
        if (this.isOESFBSupported) {
            GLES11Ext.glBindFramebufferOES(36160, this.mOESFBO);
            GLES20.glActiveTexture(33984);
        } else {
            GLES20.glBindFramebuffer(36160, 0);
        }
        listIterator.next().draw(this.mGlobalTransform);
        this.mResBuffer.position(0);
        GLES20.glReadPixels(0, 0, i2, i4, 6408, 5121, this.mResBuffer);
        Utils.checkGLErr();
        this.mResBuffer.position(0);
        GLES11Ext.glBindFramebufferOES(36160, 0);
        GLES20.glBindFramebuffer(36160, 0);
        bitmap.copyPixelsFromBuffer(this.mResBuffer);
        this.mTempCanvas.setBitmap(bitmap);
        addSignatureInfo(bitmap);
    }

    public int getCurrentTexture() {
        return this.mCurrentTexture;
    }

    public void setupGlobalTransform(int i, int i2, Mode mode) {
        Matrix.setIdentityM(this.mGlobalTransform, 0);
        int i3 = AnonymousClass1.$SwitchMap$com$sonymobile$generativeartwork$render$OffscreenRenderer$Mode[mode.ordinal()];
        if (i3 != 1) {
            if (i3 != 2) {
                return;
            }
            Matrix.scaleM(this.mGlobalTransform, 0, 1.0f, -1.0f, 1.0f);
            if (i > this.mWidth || i2 > this.mHeight) {
                return;
            }
            GLES20.glScissor(0, 0, i, i2);
            GLES20.glEnable(3089);
            this.mScissorsEnabled = true;
            return;
        }
        float[] fArr = this.mGlobalTransform;
        int i4 = this.mWidth;
        float f = (((i - i4) / 2.0f) / i4) * 2.0f;
        int i5 = this.mHeight;
        Matrix.translateM(fArr, 0, f, (((i2 - i5) / 2.0f) / i5) * 2.0f, 0.0f);
        Matrix.scaleM(this.mGlobalTransform, 0, i / this.mWidth, (i2 / this.mHeight) * (-1.0f), 1.0f);
        if (this.mScissorsEnabled) {
            GLES20.glDisable(3089);
            this.mScissorsEnabled = false;
        }
    }

    /* JADX INFO: renamed from: com.sonymobile.generativeartwork.render.OffscreenRenderer$1, reason: invalid class name */
    static /* synthetic */ class AnonymousClass1 {
        static final /* synthetic */ int[] $SwitchMap$com$sonymobile$generativeartwork$render$OffscreenRenderer$Mode;

        static {
            int[] iArr = new int[Mode.values().length];
            $SwitchMap$com$sonymobile$generativeartwork$render$OffscreenRenderer$Mode = iArr;
            try {
                iArr[Mode.Stretch.ordinal()] = 1;
            } catch (NoSuchFieldError unused) {
            }
            try {
                $SwitchMap$com$sonymobile$generativeartwork$render$OffscreenRenderer$Mode[Mode.CutTL.ordinal()] = 2;
            } catch (NoSuchFieldError unused2) {
            }
        }
    }

    public void resetGlobalTransform() {
        Matrix.setIdentityM(this.mGlobalTransform, 0);
        Matrix.scaleM(this.mGlobalTransform, 0, 1.0f, -1.0f, 1.0f);
        if (this.mScissorsEnabled) {
            GLES20.glDisable(3089);
            this.mScissorsEnabled = false;
        }
    }

    private void addSignatureInfo(Bitmap bitmap) {
        if (mSignatureLength * 8 < bitmap.getByteCount() * 4) {
            int i = mNumSignaturePxls;
            int width = i > bitmap.getWidth() ? bitmap.getWidth() : i;
            int width2 = i / bitmap.getWidth();
            if (i % bitmap.getWidth() != 0) {
                width2++;
            }
            if (width2 > bitmap.getHeight()) {
                width2 = bitmap.getHeight();
            }
            int i2 = width2;
            int i3 = width * i2;
            if (i < i3 && this.mSignaturePixels.length < i3) {
                this.mSignaturePixels = new int[i3];
            }
            bitmap.getPixels(this.mSignaturePixels, 0, bitmap.getWidth(), 0, 0, width, i2);
            int i4 = 0;
            for (int i5 = 0; i5 < mSignatureLength; i5++) {
                int[] iArr = this.mSignaturePixels;
                int i6 = i4 + 1;
                iArr[i6] = iArr[i6] & (-16843010);
                int i7 = iArr[i6];
                byte[] bArr = mSignatureData;
                iArr[i6] = i7 | (((bArr[i5] >> 0) & 1) << 0);
                iArr[i6] = iArr[i6] | (((bArr[i5] >> 1) & 1) << 8);
                iArr[i6] = iArr[i6] | (((bArr[i5] >> 2) & 1) << 16);
                iArr[i6] = iArr[i6] | (((bArr[i5] >> 3) & 1) << 24);
                iArr[i4] = iArr[i4] & (-16843010);
                iArr[i4] = iArr[i4] | (((bArr[i5] >> 4) & 1) << 0);
                iArr[i4] = iArr[i4] | (((bArr[i5] >> 5) & 1) << 8);
                iArr[i4] = iArr[i4] | (((bArr[i5] >> 6) & 1) << 16);
                iArr[i4] = iArr[i4] | (((bArr[i5] >> 7) & 1) << 24);
                i4 += 2;
            }
            bitmap.setPixels(this.mSignaturePixels, 0, bitmap.getWidth(), 0, 0, width, i2);
            return;
        }
        throw new IllegalArgumentException("Too large string for hiding");
    }

    public boolean checkSignatureInfo(Bitmap bitmap) {
        int height = bitmap.getHeight() * bitmap.getRowBytes();
        int i = mSignatureLength;
        if (i * 8 >= height) {
            return false;
        }
        byte[] bArr = new byte[i];
        int i2 = mNumSignaturePxls;
        int[] iArr = new int[i2];
        int width = i2 > bitmap.getWidth() ? bitmap.getWidth() : i2;
        int width2 = i2 / bitmap.getWidth();
        if (i2 % bitmap.getWidth() != 0) {
            width2++;
        }
        bitmap.getPixels(iArr, 0, bitmap.getWidth(), 0, 0, width, width2);
        int i3 = 0;
        for (int i4 = 0; i4 < i; i4++) {
            bArr[i4] = (byte) (bArr[i4] | ((byte) (((iArr[i3] >> 24) & 1) << 7)));
            bArr[i4] = (byte) (bArr[i4] | ((byte) (((iArr[i3] >> 16) & 1) << 6)));
            bArr[i4] = (byte) (bArr[i4] | ((byte) (((iArr[i3] >> 8) & 1) << 5)));
            bArr[i4] = (byte) (bArr[i4] | ((byte) (((iArr[i3] >> 0) & 1) << 4)));
            int i5 = i3 + 1;
            bArr[i4] = (byte) (bArr[i4] | ((byte) (((iArr[i5] >> 24) & 1) << 3)));
            bArr[i4] = (byte) (bArr[i4] | ((byte) (((iArr[i5] >> 16) & 1) << 2)));
            bArr[i4] = (byte) (bArr[i4] | ((byte) (((iArr[i5] >> 8) & 1) << 1)));
            bArr[i4] = (byte) (bArr[i4] | ((byte) (((iArr[i5] >> 0) & 1) << 0)));
            i3 += 2;
        }
        return Arrays.equals(bArr, mSignatureData);
    }
}
